### PR TITLE
#161075138 Login Page

### PR DESCRIPTION
**Pull request by jmusila**
**What Does This PR do?**
Creates a login user interface

**Description of Tasks to be completed?**

-  Designing and Creating a login page for the app which is also a landing page

**How should this be manually tested?**
steps for testing :
- Create a working folder on your desktop or preferred location.
- Navigate to your working folder and open a new terminal
- Type the following git clone https://github.com/jonathanmusila/store-manager.git
- Navigate to the UI and open index.html in a preferred browser.

**What are the relevant pivotal tracker stories?**
Story-ID  #161075138

**Screenshot**
menu_004

### CODE REVIEW

**Comment by sharkdevs** [comment]
Good work: Nice UI
**Recommendations**
1. Check the naming of the PR

**Comment by Georgeygigz** [comment]
Nyc work, but you should not raise your PR to master branch

**Comment by Deekerubo** [comment]
Awesome work, rename your title according to the naming conventions given `#ID LogIn`

**Comment by Paulvitalis200** [comment]
Good work

**Comment by Teatoller** [comment]
Hello, Jonathan,
Nice choice of background image. You might one to give prominence to the login area to make it stand out and not be swallowed. For example by putting a thin border around the login area. Looks very good.

Regards
Steven Ennis

**Pull request merged**
